services:
  - type: worker
    name: SpotiLoader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/sholoomail/SpotiLoader.git
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: MONGO_DB_URL 
        sync: false
